export const Menu = [
  {
    id: 1,
    image: "",
    name: "pizza",
    category: "dinner",
    price: "290💲",
    decription: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 2,
    image: "",
    name: "South Indian",
    category: "dinner",
    price: "380💲",
    decription: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 3,
    image: "",
    name: "Idaly Sambhar",
    category: "breakfast",
    price: "30💲",
    decription: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 4,
    image: "",
    name: "Gujarati Thali",
    category: "lunch",
    price: "480💲",
    decription: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 5,
    image: "",
    name: "Punjabi Thali",
    category: "lunch",
    price: "300💲",
    decription: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 6,
    image: "",
    name: "Bateka-Pauva",
    category: "breakfast",
    price: "60💲",
    decription: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 7,
    image: "",
    name: "Chinese",
    category: "evening",
    price: "150💲",
    decription: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 8,
    image: "",
    name: "Bhaji-Paw",
    category: "evening",
    price: "80💲",
    decription: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: 9,
    image: "",
    name: "Ice-Creame",
    category: "evening",
    price: "50💲",
    decription: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
  },
]
